### ISSUE TITLE
VSCode Remote Tunnel background system service requires restart after login/logout

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo_app#114]
It appears that if the user has installed VSCode Remote Tunnel background system service and logs out, service still keeps the user login until it is restarted. The same issue applies to login (service won't detect a login until a restart).

To address this, I suggest adding a `Service` or `Manage Service` menu item that when pressed presents the user with following options:

- Install/Uninstall Service
- Restart 
- Stop
- Start (might not be needed...)

This way the user can explicitly restart the service manually with this option after logging in and logging out.

We need to also make it clear in the UI that a service restart is required for login and logout to take effect after the service is installed and running.

**Comment by mehrdadfeller** [comment]
to reproduce this issue log in once, then install service, then logout and try to login again and you won't be able to connect to tunnel.

**Comment by sassanh** [comment]
Done in b79e84dc319d9027aa840a0baf481169bbf50a2b
