### ISSUE TITLE
Consider piper as an offline text to speech engine

### ISSUE THREAD

**Issue by sassanh** [ubopod/ubo_app#120]
Picovoice works fine, but it has the api key barrier, even though it is free and everyone can get an api key, it is probably not convenient for the user to sign up in picovoice, find the api key, qr code it and scan it.
So we can consider [Piper](https://github.com/rhasspy/piper) as the default text to speech engine.

**Comment by mehrdadfeller** [comment]
add `piper` and linux `espeak` under accessibility->voice options. I suggest we make `piper` the default but allow used to change default by entering each option and selecting `default` option.
