### ISSUE TITLE
pre-install vim on generated .img

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo_app#140]
possibly we can have a pre-configured version of vim or neovim preinstalled for developers. the goal is to enhance the editor experience in shell environment. open to suggestions

**Comment by sassanh** [comment]
Aren't `nano` and `vi` already installed? I see both on my ubo-pod, I'm running a light version.
Since I never installed vim nor nano (I usually go with neovim) I assume they were both preinstalled.

**Comment by sassanh** [comment]
Could it be that you are trying `vim` command instead of `vi`?
