### ISSUE TITLE
Power button is missing an icon

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo_app#151]
Home -> Power -> Poweroff is missing an icon. let's use something like this icon fron nerdfont:

nf-iec-power

**Comment by sassanh** [comment]
@mehrdadfeller it does have an icon:

![Image](https://github.com/user-attachments/assets/872eec18-1d4a-43c5-9c23-fc825402180a)

It is `md-power-off` which is simply an empty circle. But seems like it is a bit misleading as one may think the icon is not loaded.
