### ISSUE TITLE
remote vscode tunnel support

### ISSUE THREAD

**Issue by zytegalaxy** [ubopod/ubo_app#17]
Dev tunnels can also be used to access local web services similar to ngrok

https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/overview
https://code.visualstudio.com/docs/remote/tunnels

I have a basic implementation of this here but it is not very stable:
https://github.com/ubopod/ubo-sdk/blob/43b7ed7497a61cf7982129c908a2f84e35166a79/device/device.py#L92

**Comment by sassanh** [comment]
We need the user to accept their license agreement somehow, I'm not sure if it's legally enough to show a qr code link to their agreement page with an accept menu item button?

**Comment by ubopod** [comment]
You can run the command with a flag to automatically accept the license agreement for now. We can later do that through a popover with the yes/no options and qr code link to the agreement document...

**Comment by mehrdadfeller** [comment]
"--accept-server-license-terms"

**Comment by mehrdadfeller** [comment]
Yes it makes sense.

We can have a dedicated widget for Terms of Service which would have three
buttons on the left hand side mapped to three actions:

- Read
- Accept
- Decline

When the user clicks on read button, we can show a QR code that they scan
and it will redirect them to the terms of service that they can read.
