### ISSUE TITLE
WiFi sometimes gets added a few times  

### ISSUE THREAD

**Issue by zytegalaxy** [ubopod/ubo_app#46]
sometimes several duplicates show up after adding WiFi Network under `select`. Deleting one results in deleting all which is fine. Perhaps before adding a duplicate, we do a check and see if the network already exists or not. This issue does not create a functionality problem but it can make UX a bit confusion.

**Comment by sassanh** [comment]
@mehrdadfeller can you confirm this issue is resolved? I haven't seen it happening for a while.

**Comment by sassanh** [comment]
@zytegalaxy I think this is already resolved
