### ISSUE TITLE
simple web dashboard to enter api token / access keys for services

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo_app#65]
Currently the only way to pass credentials/access keys to Ubo pod is through QR code. This works well for many cases and we should keep it; but I believe we need to add a very simple web dashboard where users can enter/update access keys for various services such as cloudflare tunnel, ngrok, picovice, openai, etc

The dashboard will be basically a set of input text boxes. Once the access keys are entered, user should only be able to see part of it for example `*******gxT1` and update them for security.

**Comment by zytegalaxy** [comment]
This is related to this discussion: https://github.com/ubopod/ubo_app/discussions/77
