### ISSUE TITLE
headless VNC server setup fore remote desktop access

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo_app#67]
VNC is super popular among Pi users and adding headless VNC setup can make a bunch of people happy. With Cloudflare tunnel or ngrok, they can access desktop easily from anywhere.

**Comment by zytegalaxy** [comment]
This is relevant here:

https://youtu.be/mgbTNZD1Vcw?si=uNLPTYFI4t6p0Vqi

**Comment by mehrdadfeller** [comment]
@sassanh this deems unnecessary since Raspberry Pi Connect was introduced and it is free (free vnc i believe has some limitations)
