### ISSUE TITLE
Reorganize settings items 

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo_app#69]
Some suggestions:

- Sort menu items in order of important specially when paginated 
    - For example under Settings, it should be WiFi first, then IP address, SSH, LightDM
- Alternatively try to keep the menu items limited to 3 by grouping items based on category; for example:
    - Wifi and IP addresses can go into “Network” Item and and “SSH, VScode tunnel” into a “Remote” menu item
    -  LightDM can also go into “Desktop” menu Item; we can have VNC under desktop too or under remote

Other suggestions:
- Make pagination more obvious with an arrow or animation

**Comment by sassanh** [comment]
@zytegalaxy Note that there is a fourth item (needs scroll) named "apps", it contains "docker".
