### ISSUE TITLE
VS code CLI download seems to get stuck v 0.13.5

### ISSUE THREAD

**Issue by zytegalaxy** [ubopod/ubo_app#79]
The screen gets stuck as checking... on release version `v0.13.5`

Similar to docker pull and ubp_app update progress bar discussion, adding a progress bar to indicate download status can drastically improve user experience as well.

<img width="353" alt="Screenshot 2024-05-03 at 10 58 09 AM" src="https://github.com/ubopod/ubo_app/assets/94014876/24547aee-18b8-476d-a6df-8ca267aed848">

**Comment by zytegalaxy** [comment]
@sassanh we can add the progress bar to this later. First attempt should be made to make it functional. We will revisit this later for progress bar and other UX improvements

**Comment by sassanh** [comment]
Please check it in version 0.14.0, it should get released in 30 minutes
