### ISSUE TITLE
Issues with first time wifi onboarding UX

### ISSUE THREAD

**Issue by mehrdadfeller** [ubopod/ubo_app#88]
When I press middle button the camera does not open and app goes to home screen. Release 0.14.0 Lite.

<img width="424" alt="Screenshot 2024-05-07 at 10 02 56 PM" src="https://github.com/ubopod/ubo_app/assets/3680934/3be9b91c-96c6-4f9e-bec4-ac9655dba8b1">

Also some other comments to improve UX:

1. change icon for dismiss
2. change short text to "press middle button to add WiFi network" 
3. change long text to "press middle button to add WiFi network with QR code. If you dismiss this, you can always add WiFi network through Settings->Network->WiFi->Add"

In general, we should use "x" for dismiss and trash can icon for delete.

**Comment by sassanh** [comment]
> In general, we should use "x" for dismiss and trash can icon for delete.

The action here is actually deleting, not dismissing, if you select this item, the notification will be deleted from the notification center, while if you press the physical back button on the device it will be dismissed but stays in the notification center.

I will check the issue and change the other texts quickly.
